//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olimpos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public productos()
        {
            this.ventas = new HashSet<ventas>();
        }
    
        public int id_producto { get; set; }
        public string nom_producto { get; set; }
        public int cantidad_producto { get; set; }
        public decimal precio_producto { get; set; }
        public string oferta_producto { get; set; }
        public int categoria_producto { get; set; }
        public int proveedor_producto { get; set; }
    
        public virtual categorias categorias { get; set; }
        public virtual proveedores proveedores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ventas> ventas { get; set; }
    }
}
